// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryyhjtzecstlxozngsfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5eWhqdHplY3N0bHhvem5nc2ZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTg2MzYsImV4cCI6MjA2MTkzNDYzNn0.8xp48thvuEXHzkIHq2bayU7wzLzWQ33vmOLZtTiEzME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);